name: Build K2P A1 ImmortalWrt PassWall2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 5'

env:
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          clang \
          flex \
          bison \
          g++ \
          gawk \
          gettext \
          git \
          libncurses-dev \
          libssl-dev \
          python3 \
          rsync \
          unzip \
          zlib1g-dev \
          file

    - name: Clone ImmortalWrt
      run: |
        git clone --depth=1 \
        -b master \
        https://github.com/immortalwrt/immortalwrt.git \
        openwrt

    - name: Add PassWall2
      run: |
        chmod +x diy-part2.sh
        ./diy-part2.sh

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load config
      run: |
        cp .config openwrt/.config

    - name: Apply custom settings
      run: |
        chmod +x diy-part1.sh
        ./diy-part1.sh

    - name: Prepare config
      run: |
        cd openwrt

        sed -i '/CONFIG_PACKAGE_libselinux/d' .config
        echo '# CONFIG_PACKAGE_libselinux is not set' >> .config

        make defconfig
        
    - name: Download packages
      run: |
        cd openwrt
        make download -j8

    - name: Compile firmware
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: K2P-A1-PassWall2
        path: openwrt/bin/targets/ramips/mt7621/*
